### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by Mailaender** [mknejp/delete-release-assets#12]
I suspect some kind of API change happened as it can detect, but not delete assets:

```
Run mknejp/delete-release-assets@v1
Looking for release with tag 'monthly'...
Found release 'IP2Location™ LITE IP-COUNTRY Database' with 1 assets.
  45201674 'IP2LOCATION-LITE-DB1.IPV6.BIN.1.ZIP'
matching against:
  'IP2LOCATION-LITE-DB1.IPV6.BIN.1.ZIP'
delete matching assets:
  45201674 'IP2LOCATION-LITE-DB1.IPV6.BIN.1.ZIP'
Error: Not Found
```

https://github.com/OpenRA/GeoIP-Database/runs/3652409047?check_suite_focus=true

**Comment by mknejp** [comment]
Interesting. Not much information to go by in the output. I will have a look.

**Comment by Mailaender** [comment]
As discussed in https://github.com/cb80/pubrel/issues/74 this is just the wrong error message for missing user permissions.

**Comment by mknejp** [comment]
That was my suspicion as well, as I saw that the other actions you tried had the same problem. GitHub frequently gives 404 errors instead of 403 so unauthorized users can't deduce the existence of things they aren't supposed to know about.
