### ISSUE TITLE
[Request] Option to prevent failure if no file is specified

### ISSUE THREAD

**Issue by ThePoorPilot** [mknejp/delete-release-assets#6]
I use this action on my latest project(manjaro-removed-pkgs). 

I've run into some failures with this message: "Error: At least one file name or pattern must be specified."

The actions on my project are very conditional. Circumstances are not exactly the same from build to build. I attempted to remedy this failure with an if statement based upon the contents of a file, but there are conditions (such as when brand new packages not previously seen on the repo are released) that still force the failure.

Would it be possible to add a "fail-if-not-specified" option?

In the mean time, I have thought of a temporary workaround. In my case, I could add a line with the word "placeholder" to the text file that lists files that need to be removed. This would work with the currently existing fail-if-no-assets option.

**Comment by ThePoorPilot** [comment]
I think I have found a solution in my particular script, but it would be still nice to still have the option. 
I have limited understanding of how this action works.

If it is a lot of work, it seems like a simple if statement in the yaml file can address this problem pretty effectively. I just had to fix it for my use case.

**Comment by mknejp** [comment]
Do I understand correctly, that you want a way to have an empty `assets` list and have the action do nothing in that case?

**Comment by ThePoorPilot** [comment]
Yep!

In my case, the files that need to be removed are determined each time the action is run.

On some runs, there is nothing that needs to be removed. Currently, this will cause the delete-release-assets step to fail.

I am asking for an option to have the action do nothing or not cause a failure if there are no specified assets.

I apologize for not writing this out clearer initially.

**Comment by mknejp** [comment]
I would certainly prefer if you made it work with `if` because that's its purpose. But I can see how that could be tricky given the limited tools of the workflow file. I will consider adding it.

**Comment by ThePoorPilot** [comment]
Alright, thanks for considering it.

yaml conditionals aren’t too hard, but yaml is most definitely not the same as shell scripts.

What really messed me up is that I needed my variable to be multi-lined. I had to pull a little workaround from someone’s blog to get it to work.

Anyways, for now, I think I’ve got something decent enough. I was just considering the fact that other users might have the same use case.

**Comment by ThePoorPilot** [comment]
For now, this is a maybe

**Comment by mknejp** [comment]
> What really messed me up is that I needed my variable to be multi-lined. I had to pull a little workaround from someone’s blog to get it to work.

This sounds like a usability issue and that's something I should probably address.

**Comment by ThePoorPilot** [comment]
I guess it could be good if there is a way to specify the files in order with semicolons.

In my case, the variable I am using is the contents of a file using cat.

In the generate files_to_delete.txt step on my workflow. You can see how this is addressed https://github.com/ThePoorPilot/manjaro-removed-pkgs/blob/main/.github/workflows/build.yml

Even if you do add an option where you can specify a list using semicolons, it will still require some shell scripting to work. In my case, I would need to add a semicolon to the beginning of the lines after the file is generated and then move them all to the same line.

I don’t know which approach is better. I think the multi-line approach might be easier, but doing it is not well documented by GitHub.

Here is the blog post: https://trstringer.com/github-actions-multiline-strings/

**Comment by mknejp** [comment]
> I guess it could be good if there is a way to specify the files in order with semicolons.

I was thinking that too. I didn't consider the use case where this list is generated dynamically. Forcing GitHub's multiline handling here is not great. I will probably add a mix where each line might contain semicolon-separated files and it all gets merged together. That also should be backwards compatible.
