### ISSUE TITLE
worked fine until 3 days ago

### ISSUE THREAD

**Issue by chrislusf** [mknejp/delete-release-assets#7]
thanks for this github action. I am using it in https://github.com/chrislusf/seaweedfs/actions/workflows/cleanup.yml

It has been running fine until 3 days ago.  e.g., https://github.com/chrislusf/seaweedfs/runs/2403198476 

Any clue how to fix it?

**Comment by ThePoorPilot** [comment]
I have not noticed an issue. Several assets have been removed from a release in one of my repos today without issue.

The issue on your end looks like it deals with the tag name.
It does look like you have a release with tag “dev,” so I don’t know exactly where the problem is coming from.

**Comment by ThePoorPilot** [comment]
Actually, I’m not sure I’ve tested deleting recently. Perhaps the rest API has changed. I’ll try doing a test on my end soon

**Comment by mknejp** [comment]
Looks like the workflow is succeeding again https://github.com/chrislusf/seaweedfs/actions/runs/773366796

So I assume the issue was somewhere else?

**Comment by ThePoorPilot** [comment]
I also can confirm that I was able to successfully use this tool last night.
It seems like it may have also been resolved on your end anyways!

**Comment by chrislusf** [comment]
Thanks! Somehow it works again.
